# _config.yml

# Configuration des permaliens pour supprimer les extensions .html
permalink: /:name/

# Désactiver les fonctionnalités par défaut de Jekyll pour éviter la conversion automatique des fichiers
markdown: kramdown
kramdown:
  input: GFM

# Empêcher Jekyll de traiter les fichiers HTML s'ils existent déjà
exclude:
  - index.html
  - cybercompanion.html
  - 404.html
# Désactiver Jekyll (si besoin, mais pas forcément nécessaire sur GitHub Pages)
# jekyll: false
